name: Test

on: [push]

jobs:
  job-name:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
  
      - name: Run Swift Tests
        uses: feather-actions/run-swift-tests@0.0.2
        with:
          code-coverage: true
          use-testify: true
